### ISSUE TITLE
Add CTDS Featured Image Functionality

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#48]
## Part 3 of 4 CTDS releases

Move this ticket to the sprint backlog once the feature has been built and QA'ed. 
When the feature is released, this will be moved to the done column.

## Resources
[October Mockup 2020](https://trello-attachments.s3.amazonaws.com/5c17dc735e6e6c1c9e791dfc/5eeb738ba7298126c010ec43/282de4e2112d7160af93ef545d2f5867/CTDS%2BOEC.jpg)
[CT Design System](https://projects.invisionapp.com/boards/TG3ZKWUCF5S)

# Release Checklist 
- [x] Amelia moves this ticket to sprint backlog once the feature has been built and QA'ed in stage.
- [x] Amelia confirms release time, date, and team availability: **Thursday at 9am**
- [ ] Matt launches feature
- [ ] Adam and Amelia both run through QA checklist. If QA does not pass, enact rollback plan. 
- [ ] Wait 24 hours post-release. Then Amelia closes ticket

## QA for production
- [x] Clear EVERY cache 
- [ ] Product requirements and design requirements are met in chrome, safari, edge and internet explorer
- [ ] Product requirements and design requirements are met when viewed in desktop, mobile and tablet 
- [ ] Any bugs found during stage and production QA that did not fit in this release are consolidated, folded into a new issue, and included in next release. 

## Rollback Plan
If feature does not pass QA
- [ ] Remove feature from production
- [ ] Team sync, prioritize next steps:
  - [ ] Re-release at 9am on Friday OR
  - [ ] Roll into next sprint release
