### ISSUE TITLE
Update CTDS Callout Boxes in production

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#50]
## Part 2 of 4 CTDS releases

Move this ticket to the sprint backlog once the feature has been built and QA'ed. 
When the feature is released, this will be moved to the done column.

## Resources
[October Mockup 2020](https://trello-attachments.s3.amazonaws.com/5c17dc735e6e6c1c9e791dfc/5eeb738ba7298126c010ec43/282de4e2112d7160af93ef545d2f5867/CTDS%2BOEC.jpg)
[CT Design System](https://projects.invisionapp.com/boards/TG3ZKWUCF5S)

# Release Checklist 
- [x] Amelia moves this ticket to sprint backlog once the feature has been built and QA'ed in stage.
- [x] Amelia confirms release time, date, and team availability: **Thursday at 9am**
- [x] Matt launches feature
- [x] Adam and Amelia both run through QA checklist. If QA does not pass, enact rollback plan. 
- [x] Wait 24 hours post-release. Then Amelia closes ticket

## QA for production
- [x] Clear EVERY cache 
- [x] Product requirements and design requirements are met in chrome, safari, edge and internet explorer
- [x] Product requirements and design requirements are met when viewed in desktop, mobile and tablet 
- [x] Any bugs found during stage and production QA that did not fit in this release are consolidated, folded into a new issue, and included in next release. 

## Rollback Plan
If feature does not pass QA
- [ ] Remove feature from production
- [ ] Team sync, prioritize next steps:
  - [ ] Re-release at 9am on Friday OR
  - [ ] Roll into next sprint release

**Comment by AmeliaWellers** [comment]
Issue: If a user does *not* select a horizontal or card layout, the callout box displays stripped of any styling. 
Intended behavior: If a user does not select a horizontal or card layout, the callout box defaults to horizontal, and all CSS styling is included.

Will wrap this into the next sprint

**Comment by admoorgit** [comment]
Styling adjustments for callouts based on most recent CTDS values and some custom tweaks (pulled from STAGE ticket)

Purple Bar on Horizontal + Card:
- border-left-width (or top-width on card): .375rem solid #61366F
- border-radius: .25rem;

Horizontal Margin:
- margin-bottom: .275rem;

Card Margin:
- margin-bottom: .5rem;

Shadow for both:
- box-shadow: .1rem, .25rem 1.25 rem rgba(97,54,111,.1)

Icons:
- color: #61366F
– SVG width and max-height: 2.5rem

Visual builder:
- Possible to make the icon preview much smaller? Like 50x50px?
- Can we make the "title" read out in the visual builder BOLD so it sticks out a lil more? I think the current alert box shows it as an H3 or something.

**Comment by admoorgit** [comment]
Hi! Here's a suggestion for a tweaked order for callout box content entry. One thing we noticed while walking through it today was it is a little clunky if you're trying to go fast. So what about...

**Layout (Horizontal/Card) — If possible, make "horizontal" default
Title
Content
Icon On/Of
Icon Search**

Also, please remove the second instance of "View a full list of available icons at https://ctoec.org/oec-icons", as this info is also in context for the icon search.

**Comment by admoorgit** [comment]
Change error message for mistyping an icon name in the search.

It currently says "Invalid Post". Should be something like "No icon matches found"

**Comment by admoorgit** [comment]
@bloom-hondo a few items I've been thinking about. Can you a) let us know if it's even possible/feasible and b) if so, what is the LOE ballpark?

1. Can we make any changes to the Gutenburg visual editor so it's clear when content is an alert/callout box — OR are there any plugins that could do this? It's currently not visible until it's clicked, and I worry that'll confuse OEC. 

IF NOT, we can point them to the "List View" option that tells you everything on the page, and clicking that opens the lil editor automagically.

2. Possible to pop the whole icon list into the autocomplete and it remove items as they type?

3. Can we add UL/OL options to callout boxes? Without them, bullets don't indent properly by default, and I don't think OEC would know to edit as HTML if that's even an option within a callout box.

4. Possible to include tiny lil icon preview along with autocomplete, so users won't have to pop over to another page to cross reference? Would prefer to find a way to keep them in the editor to get the answers they need.

Dassit for now!
- a.

**Comment by admoorgit** [comment]
Changes to "TITLE" style in callout box:

font-size: 1.5rem;
margin-bottom: 1rem;

**Comment by AmeliaWellers** [comment]
@admoorgit a few answers to the q's above:

IF NOT, we can point them to the "List View" option that tells you everything on the page, and clicking that opens the lil editor automagically. --- **I think this is going to be the way to go to keep general dev costs down for a function that will be used relatively infrequently. But, we should include this in training/wordpress guide, and I'll make a callout box how-to video once the tweaks are fixed. Plus, list view is a good thing for cc's to know about***

Possible to pop the whole icon list into the autocomplete and it remove items as they type? -- **Would be great if it's easy! I had suggested a scroll bar to Matt and I think he said to add to the next tweaks, if I remember correctly. Will add to the other ticket** 

Can we add UL/OL options to callout boxes? Without them, bullets don't indent properly by default, and I don't think OEC would know to edit as HTML if that's even an option within a callout box. **-- is there an example that uses lists in callout boxes? Just curious, I didn't come across any, and I wonder if this might encourage longer callout boxes we don't want**

Possible to include tiny lil icon preview along with autocomplete, so users won't have to pop over to another page to cross reference? Would prefer to find a way to keep them in the editor to get the answers they need. **[The Sync meeting notes](https://docs.google.com/document/d/1I4NiNxWCukCNw1UFhOigVQxEmD_hCDCIaK1-4sAYEHE/edit#) have the reasoning behind why we aren't going to do this (TLDR: requires lots of dev time).**
