### ISSUE TITLE
QA Checklist and Release Plan [Template]

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#51]
# QA Checklist 
- [ ] Amelia moves QA checklist to each user story/issue 
- [ ] Round 1a: Amelia tests functions and as much accessibility as possible, report findings in ticket
- [ ] Round 1b: Adam tests functions and finishes accessibility checklist, report findings in ticket
- [ ] Round 2: Matt updates stage, Amelia and Adam confirm bug fixes in stage

## Product / Function
- [ ]  meets product requirements
- [ ]  meets design requirements 
- [ ]  meets acceptance criteria (user story) 
- [ ]  additional functions or use cases tested: 
  - [ ] 
  - [ ] 

## Accessibility
- [ ] Site doesn't timeout unexpectedly
- [ ] Default language is set
- [ ] Page is keyboard accessible and free of keyboard traps
- [ ] Page tab order is logical
- [ ] Site never loses focus
- [ ] Page titles are descriptive
- [ ] Headings are nested properly
- [ ] Text has sufficient color contrast
- [ ] Links are unique and contextual
- [ ] All relevant images use an “img” tag
- [ ] All images have alt attributes
- [ ] Multimedia is tagged
- [ ] Tables are coded properly
- [ ] Form inputs have explicit labels
- [ ] Form instructions are associated with correct inputs
- [ ] Frames (if applicable) are named
- [ ] CSS isn't required to use the page
- [ ] Flashing elements are compliant or set to static
- [ ] Required plugins are linked on the page

### Mac
- [ ] OS Catalina - Safari 13, Chrome 88, 87 (Amelia)
- [ ] OS Big Sur - Safari 14, Chrome 88, 87 (Adam)
### Windows 10 (Adam)
- [ ] Edge 88
- [ ] Safari 14, 13
- [ ] Chrome 88, 87 
- [ ] IE 11
### iOS (Amelia)
- [ ] iPhone: 12, 12 Pro Max, XR, 11, 8, Mini SE
  - [ ] Safari 14, 13
  - [ ] Chrome 88, 87 
- [ ] iPad 12 (check resolution!)
  - [ ] Safari 14, 13
  - [ ] Chrome 88, 87 
### Android (Adam) 
- [ ] Galaxy S9

### Full accessibility checklist
https://skylight.digital/work/toolkits/accessibility-guide/checklist/

# Release Plan 
- [ ] Following completion of QA checklist, Amelia moves Epic to In Progress 
- [ ] Amelia confirms release time, date, and team availability: 
- [ ] Matt launches feature
- [ ] Amelia and Adam complete Release QA checklist (below) 
- [ ] Amelia moves ticket to done

## Release QA checklist
- [ ] Clear EVERY cache 
- [ ] Product requirements and design requirements are met in
  - [ ] chrome, safari, edge and internet explorer (any device/OS)
  - [ ] desktop, mobile and tablet  (any browser/OS)
  - [ ] Windows, iOS, android, Mac (any browser/device)
- [ ] Write bugs in the Epic comments. Assess if rollback is necessary. 
- [ ] Amelia consolidates bugs and folds into a new issue for next release.

## Rollback plan
If feature does not pass QA
- [ ] Remove feature from production
- [ ] Team sync, prioritize next steps:
  - [ ] Re-release at 9am on Friday OR
  - [ ] Roll into next sprint release
