### ISSUE TITLE
Add ct.gov header to production

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#71]
# Part 1 of 4 CTDS releases

### Product Requirements
- CT logo is present
- Google Translation dropdown is present and functions across every page in the main navigation
 
### Design requirements
- CT logo is the most up to date logo available
- header matches CTDS design system requirements
- header meets Section 508c accessibility requirements 

### Acceptance criteria
- Header passes QA and release checklist

# Release Checklist 
- [x] Amelia moves this ticket to sprint backlog once the feature has been built and QA'ed in stage.
- [x] Amelia confirms release time, date, and team availability: **Thursday at 9am**
- [x] Matt launches feature
- [x] Adam and Amelia both run through QA checklist. If QA does not pass, enact rollback plan. 
- [x] Wait 24 hours post-release. Then Amelia closes ticket

## QA for production
- [x] Clear EVERY cache 
- [x] Product requirements and design requirements are met in chrome, safari, edge and internet explorer
- [x] Product requirements and design requirements are met when viewed in desktop, mobile and tablet 
- [x] Any bugs found during stage and production QA that did not fit in this release are consolidated, folded into a new issue, and included in next release. 

### Bonus QA 
(because Amelia did not include into product requirements, my bad)
- [x] After clicking on any language in the header, the ct.gov header is still visible
- [ ] After clicking on any language in the header, the language translation in the ct.gov header still functions (*still doesn't work in chrome*)

## Rollback Plan
If feature does not pass QA
- [ ] Remove feature from production
- [ ] Team sync, prioritize next steps:
  - [ ] Re-release at 9am on Friday OR
  - [ ] Roll into next sprint release

## Resources
[October Mockup 2020](https://trello-attachments.s3.amazonaws.com/5c17dc735e6e6c1c9e791dfc/5eeb738ba7298126c010ec43/282de4e2112d7160af93ef545d2f5867/CTDS%2BOEC.jpg)
[CT Design System](https://projects.invisionapp.com/boards/TG3ZKWUCF5S)
