### ISSUE TITLE
Closeout Tasks

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#92]
## WordPress Tasks 
- [x] [All plugins are updated ](https://app.zenhub.com/workspaces/oec-website-product-board-600732ace98820000e3ffaea/issues/ctoec/ctoec/107)
- [ ] All Genesis/WordPress bugs have been submitted to Genesis/WordPress ([make icon library visible from block editor](https://app.zenhub.com/workspaces/oec-website-product-board-600732ace98820000e3ffaea/issues/ctoec/ctoec/90)) ([custom block disappears in page editor](https://app.zenhub.com/workspaces/oec-website-product-board-600732ace98820000e3ffaea/issues/ctoec/ctoec/89))
- [ ] [The live environment has been replicated to the staging environment](https://app.zenhub.com/workspaces/oec-website-product-board-600732ace98820000e3ffaea/issues/ctoec/ctoec/112)
- [ ] [Dev.ctoec.org has been deleted ](https://app.zenhub.com/workspaces/oec-website-product-board-600732ace98820000e3ffaea/issues/ctoec/ctoec/113)

## GitHub tasks
- [x] [Consolidate Repos and Add Lando](https://app.zenhub.com/workspaces/oec-website-product-board-600732ace98820000e3ffaea/issues/ctoec/ctoec/56)
- [x] [Resolve Dependabot dependency conflicts ](https://app.zenhub.com/workspaces/oec-website-product-board-600732ace98820000e3ffaea/issues/ctoec/ctoec/108)
- [x] Wikis are up to date and descriptive  
- [x] [Hand over full access to repo to United Way](https://app.zenhub.com/workspaces/oec-website-product-board-600732ace98820000e3ffaea/issues/ctoec/ctoec/116)

## Reference 
 [OEC Website Handoff Plan ](https://docs.google.com/document/d/1JQBBSlxfpwucqaZxLJZkmjaMi40QycQc5S2axI6bUF0/edit)
